### ISSUE TITLE
Error: [$compile:multidir]

### ISSUE THREAD

**Issue by nickserv** [rit-sse/QDB-2.0#8]
I am getting the following routing error (in Angular) on all pages within `/qdb`. Nothing on the page loads under the navbar (not sure if this is intentional or due to the error).

> Error: [$compile:multidir] Multiple directives [ngController, paperDialog] asking for new/isolated scope on: `<paper-dialog ng-controller="AddController" id="addDialog" heading="Add a Quote">`

https://docs.angularjs.org/error/$compile/multidir?p0=ngController&p1=paperDialog&p2=new%2Fisolated%20scope&p3=%3Cpaper-dialog%20ng-controller%3D%22AddController%22%20id%3D%22addDialog%22%20heading%3D%22Add%20a%20Quote%22%3E

**Comment by kristenmills** [comment]
What browser and OS?

**Comment by nickserv** [comment]
Firefox 33.0a2 (Aurora channel) on Mac OS 10.7.5 (Lion).

**Comment by kristenmills** [comment]
Interesting.  I have no problem with it on that version of firefox. I'll try a couple things but you are going to have to test them for me.

**Comment by nickserv** [comment]
I am also seeing this issue on Firefox 31 (release channel), Chrome 36, and Safari 6.1.6. It seems like this is an issue with the Rails app. Would you like to see any logs?

**Comment by kristenmills** [comment]
I mean it's clearly an angular issue. But I'm not having this issue lol.

**Comment by nickserv** [comment]
I know the error is in Angular. However, I can't find a browser on my machine that doesn't have this issue, and it seems like you're not seeing this at all, so I'm suspecting that something about how the Rails app is running on my computer is causing this issue.

**Comment by kristenmills** [comment]
Well I'll look into it tomorrow. There is one specific thing I want to try and so i'll put it on some hotfix branch and see if it helps.

**Comment by kristenmills** [comment]
I updated to angular 1.3 and ran into the problem.

**Comment by kristenmills** [comment]
I fixed it
